### ISSUE TITLE
"Cannot convert undefined or null to object" on Dashboard

### ISSUE THREAD

**Issue by barillabartus** [avarixe/myfifa-vue#304]
Hey, I just recently discovered this while looking for an app or website to track my own Career Mode. I don't want to be a dick because idk if this program is finished yet, but going to the dashboard results in a "Cannot convert undefined or null to object" error. 

Also I've added all my players but they're not visible in Squad Creator or wherever.

**Comment by avarixe** [comment]
Thanks for reporting this bug! A fix has been made and applied to the website concerning the dashboard page.
